default:
 properties:
  proxy.enabled: false
  proxy.ip: 127.0.0.1
  proxy.port: 9000
  allure.report: true
  allure.create.enviroment: true
  webdriver.cap.recordVideo: false
  webdriver.cap.maxInstances: 1
  webdriver.maximize: true
  webdriver.chrome.headless: false
 contexts: [chrome,rel]

contexts:
 chrome:
  webdriver.cap.browserName: chrome
 firefox:
  webdriver.cap.browserName: firefox
 qa:
  author.url: qaAuthorUrl
  author.ip: qaAuthorIp
  author.login: qaAuthorLogin
  author.password: qaAuthorPassword
  publish.url: qaPublishUrl
  publish.ip: qaPublishIP
 rel:
  author.url: relAuthorUrl
  author.ip: relAuthorIp
  author.login: relAuthorLogin
  author.password: relAuthorPassword
  publish.url: relPublishUrl
  publish.ip: relPublishIP